[package]
name = "s2binlib_binding"
version = "0.1.0"
edition = "2024"

[lib]
name = "s2binlib"
crate-type = ["staticlib", "cdylib"]

[features]
default = []
debug_c_bindings = []

[dependencies]
once_cell = "1.20"
s2binlib = { path = "../s2binlib" }

